//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMART1Entities1 : DbContext
    {
        public CMART1Entities1()
            : base("name=CMART1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Bill> Bills { get; set; }
        public DbSet<Bill_List> Bill_List { get; set; }
        public DbSet<BranchImport> BranchImports { get; set; }
        public DbSet<BranchImport_List> BranchImport_List { get; set; }
        public DbSet<HeadImport> HeadImports { get; set; }
        public DbSet<HeadImport_List> HeadImport_List { get; set; }
        public DbSet<PriceHistory> PriceHistories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Promotion> Promotions { get; set; }
        public DbSet<requestImport> requestImports { get; set; }
        public DbSet<requestImport_List> requestImport_List { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
